import { z } from "zod";
import { randomUUID } from "node:crypto";
import { writeUnderSandbox } from "./sandbox";

export const emailDraftInputSchema = z.object({
  to: z
    .array(z.string().email())
    .min(1)
    .describe("Recipient email addresses."),
  subject: z.string().min(1).max(180),
  body: z
    .string()
    .min(1)
    .describe("Plain-text or Markdown body. Will be saved as Markdown."),
  cc: z.array(z.string().email()).default([]),
});

export type EmailDraftResult = {
  draft_id: string;
  path: string;
  bytes: number;
  rendered: string;
  disclaimer: string;
};

export async function emailDraft(
  input: z.infer<typeof emailDraftInputSchema>,
): Promise<EmailDraftResult> {
  const id = randomUUID();
  const rendered = [
    `# Draft email · ${id}`,
    "",
    `**To:** ${input.to.join(", ")}`,
    input.cc.length ? `**CC:** ${input.cc.join(", ")}` : null,
    `**Subject:** ${input.subject}`,
    "",
    "---",
    "",
    input.body,
    "",
    "---",
    "",
    "_Generated by draft-actions-mcp. Nothing was sent._",
  ]
    .filter((line) => line !== null)
    .join("\n");

  const { path, bytes } = await writeUnderSandbox(
    `emails/${id}.md`,
    rendered,
  );

  return {
    draft_id: id,
    path,
    bytes,
    rendered,
    disclaimer:
      "Email NOT sent. Draft saved to a sandboxed /tmp directory only. No SMTP, no SES, no MTA.",
  };
}
